# Generated by Django 5.2.3 on 2025-07-02 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='general_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'gm'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('hr', 'HR'), ('gm', 'General Manager')], max_length=10),
        ),
    ]
