# Generated by Django 5.2.3 on 2025-07-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_general_manager_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='department_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='supervisor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
