# Generated by Django 5.2.3 on 2025-07-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employeeprofile_date_of_joining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='hr_role',
            field=models.CharField(choices=[('general', 'General HR'), ('payroll', 'Payroll HR'), ('training', 'Training HR')], default='general', max_length=50),
        ),
    ]
