# Generated by Django 5.2.3 on 2025-07-07 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_taxrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('trainer', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending')], default='ENROLLED', max_length=20)),
                ('attendance', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employeeprofile')),
                ('training_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.trainingprogram')),
            ],
        ),
    ]
